// Generated by scripts/gen-build-info.mjs - do not edit manually.
export const BUILD_COMMIT = "ad45a72001bc700c19d941e28a341b37bc0b58bb" as const;
export const APP_VERSION = "1.1.0" as const;

export const APP_NAME = "Codexa";
export const CODEXA_CHANNEL_ENV = "CODEXA_CHANNEL" as const;
export const LOCAL_DEV_CHANNEL = "local-dev" as const;
export type BuildChannel = "published" | typeof LOCAL_DEV_CHANNEL | string;

export interface AppBuildInfo {
  appName: string;
  version: string;
  channel: BuildChannel;
  isDev: boolean;
  commit: string | null;
  displayVersion: string;
  brandLabel: string;
}

export function getBuildChannel(env: NodeJS.ProcessEnv = process.env): BuildChannel {
  return env[CODEXA_CHANNEL_ENV]?.trim() || "published";
}

export function isDevBuild(env: NodeJS.ProcessEnv = process.env): boolean {
  return getBuildChannel(env) === LOCAL_DEV_CHANNEL;
}

export function formatDisplayVersion(
  version: string = APP_VERSION,
  env: NodeJS.ProcessEnv = process.env,
): string {
  return isDevBuild(env) ? `${version}-dev` : version;
}

export function formatBrandLabel(env: NodeJS.ProcessEnv = process.env): string {
  return `${APP_NAME} v${formatDisplayVersion(APP_VERSION, env)}`;
}

export function getAppBuildInfo(env: NodeJS.ProcessEnv = process.env): AppBuildInfo {
  const channel = getBuildChannel(env);
  const displayVersion = formatDisplayVersion(APP_VERSION, env);
  return {
    appName: APP_NAME,
    version: APP_VERSION,
    channel,
    isDev: channel === LOCAL_DEV_CHANNEL,
    commit: String(BUILD_COMMIT) && String(BUILD_COMMIT) !== "unknown" ? String(BUILD_COMMIT) : null,
    displayVersion,
    brandLabel: `${APP_NAME} v${displayVersion}`,
  };
}
